server:
  port: 8080
spring:
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://10.12.159.25:3306/car?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.j1902.pojo
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true



