
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.12.159.25:3306/car?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml

